// import { Chat, ChatUser } from '@/types/chat.types';

// // The logged-in user (simulated – matches what would come from auth store)
// export const ME: ChatUser = {
//   id: 'me-001',
//   name: 'Alex Johnson',
//   avatar: undefined,
//   isOnline: true,
// };

// // ─── Mock Chats ──────────────────────────────────────────────────────────────
// export const MOCK_CHATS: Chat[] = [
//   // ── Chat 1: Priya Sharma (rich conversation history) ──────────────────────
//   {
//     id: 'chat-001',
//     participant: {
//       id: 'user-001',
//       name: 'Priya Sharma',
//       avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Priya',
//       isOnline: true,
//     },
//     lastMessage: 'Can we catch up tomorrow? 😊',
//     lastMessageTime: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
//     unreadCount: 2,
//     isPinned: true,
//     messages: [
//       {
//         id: 'msg-001-1',
//         chatId: 'chat-001',
//         senderId: 'user-001',
//         content: 'Hey Alex! How are you doing? 👋',
//         timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
//         status: 'read',
//         isMine: false,
//       },
//       {
//         id: 'msg-001-2',
//         chatId: 'chat-001',
//         senderId: 'me-001',
//         content: 'Priya! Great to hear from you. All good here, busy with work. You?',
//         timestamp: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
//         status: 'read',
//         isMine: true,
//       },
//       {
//         id: 'msg-001-3',
//         chatId: 'chat-001',
//         senderId: 'user-001',
//         content: "Same! The new project is keeping me on my toes. But it's exciting.",
//         timestamp: new Date(Date.now() - 100 * 60 * 1000).toISOString(),
//         status: 'read',
//         isMine: false,
//       },
//       {
//         id: 'msg-001-4',
//         chatId: 'chat-001',
//         senderId: 'me-001',
//         content: 'Which project? The one with the startup?',
//         timestamp: new Date(Date.now() - 95 * 60 * 1000).toISOString(),
//         status: 'read',
//         isMine: true,
//       },
//       {
//         id: 'msg-001-5',
//         chatId: 'chat-001',
//         senderId: 'user-001',
//         content: 'Yes! We are building a real-time dashboard. TypeScript + Next.js. You would love it.',
//         timestamp: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
//         status: 'read',
//         isMine: false,
//       },
//       {
//         id: 'msg-001-6',
//         chatId: 'chat-001',
//         senderId: 'me-001',
//         content: "Sounds amazing! I've been working on something similar actually 🚀",
//         timestamp: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
//         status: 'read',
//         isMine: true,
//       },
//       {
//         id: 'msg-001-7',
//         chatId: 'chat-001',
//         senderId: 'user-001',
//         content: 'No way! We should sync up and share notes.',
//         timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
//         status: 'read',
//         isMine: false,
//       },
//       {
//         id: 'msg-001-8',
//         chatId: 'chat-001',
//         senderId: 'user-001',
//         content: 'Can we catch up tomorrow? 😊',
//         timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
//         status: 'delivered',
//         isMine: false,
//       },
//     ],
//   },

//   // ── Chat 2: Rahul Mehta ───────────────────────────────────────────────────
//   {
//     id: 'chat-002',
//     participant: {
//       id: 'user-002',
//       name: 'Rahul Mehta',
//       avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Rahul',
//       isOnline: false,
//       lastSeen: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
//     },
//     lastMessage: 'The PR is merged! Great work 🎉',
//     lastMessageTime: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
//     unreadCount: 0,
//     messages: [
//       {
//         id: 'msg-002-1',
//         chatId: 'chat-002',
//         senderId: 'me-001',
//         content: 'Rahul, have you reviewed the auth PR I sent yesterday?',
//         timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
//         status: 'read',
//         isMine: true,
//       },
//       {
//         id: 'msg-002-2',
//         chatId: 'chat-002',
//         senderId: 'user-002',
//         content: 'Yes! Just finished reviewing. Left a few comments on error handling.',
//         timestamp: new Date(Date.now() - 2.5 * 60 * 60 * 1000).toISOString(),
//         status: 'read',
//         isMine: false,
//       },
//       {
//         id: 'msg-002-3',
//         chatId: 'chat-002',
//         senderId: 'me-001',
//         content: 'Got it. Fixed all the issues. Pushed a new commit.',
//         timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
//         status: 'read',
//         isMine: true,
//       },
//       {
//         id: 'msg-002-4',
//         chatId: 'chat-002',
//         senderId: 'user-002',
//         content: 'The PR is merged! Great work 🎉',
//         timestamp: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
//         status: 'read',
//         isMine: false,
//       },
//     ],
//   },

//   // ── Chat 3: Ananya Patel ──────────────────────────────────────────────────
//   {
//     id: 'chat-003',
//     participant: {
//       id: 'user-003',
//       name: 'Ananya Patel',
//       avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Ananya',
//       isOnline: true,
//     },
//     lastMessage: "Don't forget the team lunch today at 1pm!",
//     lastMessageTime: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
//     unreadCount: 5,
//     messages: [
//       {
//         id: 'msg-003-1',
//         chatId: 'chat-003',
//         senderId: 'user-003',
//         content: 'Hey! Are you joining the team lunch today?',
//         timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
//         status: 'delivered',
//         isMine: false,
//       },
//       {
//         id: 'msg-003-2',
//         chatId: 'chat-003',
//         senderId: 'user-003',
//         content: "It's at Spice Garden, the new Indian place near the office 🍛",
//         timestamp: new Date(Date.now() - 3.5 * 60 * 60 * 1000).toISOString(),
//         status: 'delivered',
//         isMine: false,
//       },
//       {
//         id: 'msg-003-3',
//         chatId: 'chat-003',
//         senderId: 'user-003',
//         content: 'Riya and Karthik are also coming!',
//         timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
//         status: 'delivered',
//         isMine: false,
//       },
//       {
//         id: 'msg-003-4',
//         chatId: 'chat-003',
//         senderId: 'user-003',
//         content: 'Alex? You there?',
//         timestamp: new Date(Date.now() - 2.5 * 60 * 60 * 1000).toISOString(),
//         status: 'delivered',
//         isMine: false,
//       },
//       {
//         id: 'msg-003-5',
//         chatId: 'chat-003',
//         senderId: 'user-003',
//         content: "Don't forget the team lunch today at 1pm!",
//         timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
//         status: 'delivered',
//         isMine: false,
//       },
//     ],
//   },

//   // ── Chat 4: Dev (no unread) ───────────────────────────────────────────────
//   {
//     id: 'chat-004',
//     participant: {
//       id: 'user-004',
//       name: 'Dev Kumar',
//       avatar: undefined,
//       isOnline: false,
//       lastSeen: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
//     },
//     lastMessage: 'Sure, I will send the docs later.',
//     lastMessageTime: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
//     unreadCount: 0,
//     messages: [
//       {
//         id: 'msg-004-1',
//         chatId: 'chat-004',
//         senderId: 'me-001',
//         content: 'Hey Dev, do you have the API documentation handy?',
//         timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
//         status: 'read',
//         isMine: true,
//       },
//       {
//         id: 'msg-004-2',
//         chatId: 'chat-004',
//         senderId: 'user-004',
//         content: 'Sure, I will send the docs later.',
//         timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
//         status: 'read',
//         isMine: false,
//       },
//     ],
//   },

//   // ── Chat 5: Sneha Rao ─────────────────────────────────────────────────────
//   {
//     id: 'chat-005',
//     participant: {
//       id: 'user-005',
//       name: 'Sneha Rao',
//       avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Sneha',
//       isOnline: false,
//       lastSeen: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
//     },
//     lastMessage: 'Happy birthday!! 🎂🎉',
//     lastMessageTime: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
//     unreadCount: 1,
//     messages: [
//       {
//         id: 'msg-005-1',
//         chatId: 'chat-005',
//         senderId: 'user-005',
//         content: 'Happy birthday!! 🎂🎉',
//         timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
//         status: 'delivered',
//         isMine: false,
//       },
//     ],
//   },

//   // ── Chat 6: Arjun Nair ───────────────────────────────────────────────────
//   {
//     id: 'chat-006',
//     participant: {
//       id: 'user-006',
//       name: 'Arjun Nair',
//       avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Arjun',
//       isOnline: false,
//       lastSeen: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
//     },
//     lastMessage: 'Noted. Will check the deployment logs.',
//     lastMessageTime: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
//     unreadCount: 0,
//     messages: [
//       {
//         id: 'msg-006-1',
//         chatId: 'chat-006',
//         senderId: 'me-001',
//         content: 'The staging deployment is failing on CI. Can you take a look?',
//         timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 - 30 * 60 * 1000).toISOString(),
//         status: 'read',
//         isMine: true,
//       },
//       {
//         id: 'msg-006-2',
//         chatId: 'chat-006',
//         senderId: 'user-006',
//         content: 'Noted. Will check the deployment logs.',
//         timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
//         status: 'read',
//         isMine: false,
//       },
//     ],
//   },
// ];
